services:
  waha:
    image: devlikeapro/waha:latest
    container_name: waha-novo
    ports:
      - "3000:3000"
    environment:
      - WAHA_DASHBOARD_ENABLED=true
      - WAHA_LOG_LEVEL=info
      - WAHA_API_KEY=klara-waha-secret-key-2026
    volumes:
      - waha-sessions:/app/sessions
    restart: unless-stopped

volumes:
  waha-sessions:
